%% evalHlp_perfOverAzms
function [llhTPplacement_stats,azmsInterp] = evalHlp_perfOverAzmDists2( llhPosPlacement_all_scp_azms, ...
                                                                        scps_idxs, ...
                                                                        scp, cscp, ...
                                                                        azmFactor, ...
                                                                        allowFBc, ...
                                                                        azmSpanType, ...
                                                                        nsps, ...
                                                                        azmErrRange, ...
                                                                        useGtCorrectedAzmDistance )

if nargin < 4, azmFactor = []; end
if nargin < 5, allowFBc = []; end
if nargin < 6, azmSpanType = []; end
if nargin < 7, nsps = []; end
if nargin < 8, azmErrRange = []; end
if nargin < 9, useGtCorrectedAzmDistance = []; end

scps_idxs_ = [];
for aa = 1:4
for cbsm = 0:1    
    scpIdxs = intersect( cscp.scpMask_azmsMode(aa), scps_idxs );
    if cbsm == 1
        scpIdxs = intersect( cscp.scpMask_sideMirrorable(cbsm), scpIdxs );
    end
    scps_idxs_ = [scps_idxs_ scpIdxs]; %#ok<AGROW>
end
end
scps_idxs = scps_idxs_;

llhPosPlacement_scp_azms = llhPosPlacement_all_scp_azms(scps_idxs,:);
sceneDescr = scp(scps_idxs);

[llhTPplacement_stats,azmsInterp] = computeInterpPlacementLlh( llhPosPlacement_scp_azms, ...
                                                                        sceneDescr, ...
                                                                        azmFactor, ...
                                                                        allowFBc, ...
                                                                        azmSpanType, ...
                                                                        nsps, ...
                                                                        azmErrRange, ...
                                                                        useGtCorrectedAzmDistance );

end