function [annBscp] = getAnnotatedSegId_testSceneParams( bscp )

inf_dB = 25;
annBscp = arrayfun( @(sf)( ...
        struct( ...
        'nSrc', ...
            {sf.nSrcs-1} ...
        )...
    ), bscp );

annBscp = arrayfun( @(sf,ab)( ...
        struct( ...
        'nSrc', ...
            {ab.nSrc}, ...
        'snr', ...
            {min( inf_dB, addSnrs( sf.snrs(2:end) ) )}, ...
        'maxE', ...
            {min( [0 sf.snrs] )} ...
        )...
    ), bscp , annBscp );

annBscp = arrayfun( @(sf,ab)( ...
        struct( ...
        'nSrc', ...
            {ab.nSrc}, ...
        'snr', ...
            {ab.snr}, ...
        'maxE', ...
            {ab.maxE}, ...
        'percentageBisects', ...
            {mean(cell2mat(arrayFunAlongDim( @(a)(abs(sign(wrapTo180(sf.azms(a(1))))-sign(wrapTo180(sf.azms(a(numel(a))))))>1 & abs(sign(wrapTo180(sf.azms(a(1))-180))-sign(wrapTo180(sf.azms(a(numel(a)))-180)))>1), nchoosek(1:numel(sf.azms),min(2,numel(sf.azms))),2)))}, ...
        'percentageSrc1Bisects', ...
            {mean(abs(sign(wrapTo180(sf.azms(1)))-sign(wrapTo180(sf.azms(2:end))))>1 & abs(sign(wrapTo180(sf.azms(1)-180))-sign(wrapTo180(sf.azms(2:end)-180)))>1)}, ...
        'percentageSrc1Earsects', ...
            {mean(~(abs(sign(wrapTo180(sf.azms(1)))-sign(wrapTo180(sf.azms(2:end))))>1 & abs(sign(wrapTo180(sf.azms(1)-180))-sign(wrapTo180(sf.azms(2:end)-180)))>1) & abs(sign(wrapTo180(sf.azms(1)-90))-sign(wrapTo180(sf.azms(2:end)-90)))>1 & abs(sign(wrapTo180(sf.azms(1)+90))-sign(wrapTo180(sf.azms(2:end)+90)))>1)}, ...
        'percentageEarsects', ...
            {mean(cell2mat(arrayFunAlongDim( @(a)(~(abs(sign(wrapTo180(sf.azms(a(1))))-sign(wrapTo180(sf.azms(a(numel(a))))))>1 & abs(sign(wrapTo180(sf.azms(a(1))-180))-sign(wrapTo180(sf.azms(a(numel(a)))-180)))>1) & abs(sign(wrapTo180(sf.azms(a(1))-90))-sign(wrapTo180(sf.azms(a(numel(a)))-90)))>1 & abs(sign(wrapTo180(sf.azms(a(1))+90))-sign(wrapTo180(sf.azms(a(numel(a)))+90)))>1), nchoosek(1:numel(sf.azms),min(2,numel(sf.azms))),2)))}, ...
        'nStrongSrcs', ...
            {sum( [([sf.snrs] <= 3) isempty( sf.snrs )] )} ...
        )...
    ), bscp , annBscp );

ssks = [];
td = [];
for ii = 1 : numel( annBscp )
    snrs = bscp(ii).snrs;
    if isempty( snrs ), snrs = 0; end
    indSnrs = zeros( size( snrs ) );
    for jj = 1 : numel( snrs )
        otherIdxs = 1 : numel( snrs );
        otherIdxs(jj) = [];
        indSnrs(jj) = addSnrs( snrs(otherIdxs) - snrs(jj) );
    end
    annBscp(ii).maxSnr = min( snrs(2:end) );
    if isempty( annBscp(ii).maxSnr )
        annBscp(ii).maxSnr = 0;
    end
    annBscp(ii).isnrStd = std( indSnrs );
    annBscp(ii).isnrStd_src2to4 = std( indSnrs(2:end) );
    sazms = sort( bscp(ii).azms );
    md = min( abs( wrapTo180( sazms - [sazms(2:end) sazms(1)] ) ), abs( wrapTo180( sazms - [sazms(end) sazms(1:end-1)] ) ) );
    annBscp(ii).avgMinDist = mean( md );
    annBscp(ii).src1Azm = bscp(ii).azms(1);
end

[annBscp([annBscp.nSrc]==0).percentageBisects] = deal( 1 );
[annBscp([annBscp.nSrc]==0).percentageSrc1Bisects] = deal( 1 );
[annBscp([annBscp.nSrc]==0).isnrStd] = deal( 0 );
[annBscp([annBscp.nSrc]==0).isnrStd_src2to4] = deal( 0 );
[annBscp([annBscp.nSrc]==0).avgMinDist] = deal( 0 );

end
