function gen_segId_testdata( dd, cc, scps, azmSigm, nsbias )

startTwoEars('util/tt_segmented.config.xml');
addpath( fullfile( pwd, 'util' ) );

if nargin < 4 || isempty(azmSigm), azmSigm = 0; end
if nargin < 5 || isempty(nsbias), nsbias = 0; end

nigensPath = 'twoears/NIGENS'; % TODO: put your own NIGENS path
dataCachePath = 'twoears/idPipeCache'; % TODO: put your own (absolute!) AMLTTP cache path

segIdSuplStr = [num2str( azmSigm ) '-' num2str( nsbias )];

segmModelFileName = '70c4feac861e382413b4c4bfbf895695.mat';
mkdir( fullfile( db.tmp, 'learned_models', 'SegmentationKS' ) );
copyfile( ['../spatial_segregation_model/' segmModelFileName], ...
          fullfile( db.tmp, 'learned_models', 'SegmentationKS', segmModelFileName ), ...
          'f' );

datasets = {fullfile( nigensPath, 'NIGENS_8-foldSplit_fold1_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold2_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold3_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold4_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold5_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold6_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold7_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_8-foldSplit_fold8_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_minidebug_8-foldSplit_fold1_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_minidebug_8-foldSplit_fold2_wo_timit.flist' ),...
            fullfile( nigensPath, 'NIGENS_minidebug_8-foldSplit_fold7_wo_timit.flist' )};
if nargin < 1 || isempty( dd )
    dd = 7:8;
end

classes = {{'alarm'},{'baby'},{'femaleSpeech'},{'fire'},{'crash'},{'dog'},...
           {'engine'},{'footsteps'},{'knock'},{'phone'},{'piano'},...
           {'maleSpeech'},{'femaleScream','maleScream'}};
           
for ii = 1 : numel( classes )
    labelCreators{ii,1} = 'LabelCreators.MultiEventTypeLabeler'; %#ok<AGROW>
    labelCreators{ii,2} = {'types', classes(ii), 'negOut', 'rest', ...
                           'removeUnclearBlocks', 'time-wise',...
                           'segIdTargetSrcFilter', [1,1]}; %#ok<AGROW> % target sounds only on source 1
end
if nargin < 2 || isempty( cc ), cc = 1 : size( labelCreators, 1 ); end
           
scc = getTestSceneParametersMc7();
if nargin < 3 || isempty( scps ), scps = 1 : numel( scc ); end


lcs = {};
for ll = cc
    lcs{end+1} = feval( labelCreators{ll,1}, labelCreators{ll,2}{:} ); %#ok<AGROW>
end

fprintf( '\n\n============== gen segId mc7 %s data; dataset = %s ==============\n\n', ...
    strcat(classes{ll}{:}), num2str( dd ) );
fprintf( '\n======== azmSigm = %d, nsbias = %d. ========\n\n', ...
    azmSigm, nsbias );

pipe = TwoEarsIdTrainPipe( 'cacheSystemDir', dataCachePath, ...
                           'cacheDirectoryDirSuppl', segIdSuplStr, 'cddsUseIdxs', [4,5,6] );
pipe.blockCreator = BlockCreators.MeanStandardBlockCreator( 0.5, 1./3 );
pipe.ksWrapper = DataProcs.SegmentKsWrapper( ...
        '../spatial_segregation_model/SegmentationTrainerParameters5.yaml', ...
        'useDnnLocKs', false, ...
        'useNsrcsKs', false, ...
        'segSrcAssignmentMethod', 'minDistance', ...
        'varAzmSigma', azmSigm, ...
        'nsrcsBias', nsbias, ...
        'nsrcsRndPlusMinusBias', 0, ...
        'srcSegregateNrjThreshold', -40, ...
        'softMaskExponent', 10 ); % should be the same as featureCreator's compressor
pipe.featureCreator = FeatureCreators.FeatureSet5bBlockmean();
pipe.labelCreator = LabelCreators.MultiExecuteLabeler( lcs );
pipe.modelCreator = ModelTrainers.LoadModelNoopTrainer( 'noop' );
pipe.setTrainset( datasets(dd) );
pipe.setupData();

sc = SceneConfig.SceneConfiguration.empty;
for scp = scps
    sc(end+1) = SceneConfig.SceneConfiguration(); %#ok<AGROW>
    sc(end).addSource( SceneConfig.PointSource( ...
        'azimuth',SceneConfig.ValGen('manual',scc(scp).azms(1)), ...
        'data', SceneConfig.FileListValGen( 'pipeInput' ) )...
        );
    for jj = 2 : scc(scp).nSrcs
        sc(end).addSource( SceneConfig.PointSource( ...
            'azimuth',SceneConfig.ValGen('manual',scc(scp).azms(jj)), ...
            'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
            'offset', SceneConfig.ValGen( 'manual', 0.25 ) ), ...
            'snr', SceneConfig.ValGen( 'manual', scc(scp).snrs(jj) ),...
            'loop', 'randomSeq' ...
            );
    end
    sc(end).setLengthRef( 'source', 1, 'min', 30 );
    sc(end).setSceneNormalization( true, 1 );
end
pipe.init( sc, 'gatherFeaturesProc', false, 'fs', 16000, 'loadBlockAnnotations', true, ...
    'classesOnMultipleSourcesFilter', classes );

pipe.pipeline.dataPipeProcs{1}.dataFileProcessor.procCacheFolderNames = 'mc_test';
pipe.pipeline.dataPipeProcs{2}.dataFileProcessor.procCacheFolderNames = 'mc_test';
pipe.pipeline.dataPipeProcs{4}.dataFileProcessor.procCacheFolderNames = ...
    ['mc_segId_' segIdSuplStr '_test'];
pipe.pipeline.dataPipeProcs{5}.dataFileProcessor.procCacheFolderNames = ...
    ['mc_segId_' segIdSuplStr '_test'];
pipe.pipeline.dataPipeProcs{6}.dataFileProcessor.procCacheFolderNames = ...
    ['mc_segId_fc5b_' segIdSuplStr '_test'];


pipe.pipeline.run( 'modelPath', ['dataGen_segId' buildCurrentTimeString()], ...
    'runOption', 'onlyGenCache' );


end
